# Stock symbol selection
SAMPLE_SYMBOLS = ["NIFTY50", "NIFTY BANK", "NIFTY FIN", "NIFTY MIDCAP", "SENSEX"]

SYMBOLS = {
    'NIFTY50': '^NSEI',
    'NIFTY BANK': '^NSEBANK',
    'NIFTY FIN': 'NIFTY_FIN_SERVICE.NS',
    'NIFTY MIDCAP': 'NIFTY_MID_SELECT.NS',
    'SENSEX': '^BSESN'
}
